### ISSUE TITLE
Auto diagnostics? You mean car diagnostics?

### ISSUE THREAD

**Issue by mitar** [barracuda-fsh/pyobd#1]
I had hard time understanding what this package is about. "auto diagnostics" to means something else (automatic diagnostic .. of what). You probably want to say "car diagnostics"?

**Comment by patgd** [comment]
Auto contracts automobile.

**Comment by robheffo79** [comment]
Coming from Australia, I can see the confusion. To me also "Auto Diagnostics" reads Automatic Diagnostics.
We don't call vehicles "Automobiles", we call them "Cars".

**Comment by barracuda-fsh** [comment]
I didn't know. Thank you. I'll use cars then.

**Comment by AtesComp** [comment]
Errr, vehicles?

**Comment by patgd** [comment]
> [_Auto_: a four-wheeled vehicle designed for passenger transportation](https://www.merriam-webster.com/dictionary/auto).

**Comment by robheffo79** [comment]
> > [_Auto_: a four-wheeled vehicle designed for passenger transportation](https://www.merriam-webster.com/dictionary/auto).

While technically true, automobile is pretty much only used in the United States. Even the Wikipedia entry for Automobile redirects to Car. So, the audience who won't be confused at least initially by the name will be dwarfed by the audience who will.
