### ISSUE TITLE
[Help needed] I can't connect the OBD-II

### ISSUE THREAD

**Issue by louisonsarlinmagnus** [barracuda-fsh/pyobd#15]
Hi,

I'm using a [USB OBD-II Connector](https://www.amazon.fr/dp/B08ZDB5JBS?psc=1&ref=ppx_yo2ov_dt_b_product_details), Ubuntu 22.04 and I can't get it to work with your software (I'm using the executable in version 1.15 release on GitHub).

I've manage to connect using Putty with these settings : 
![image](https://github.com/barracuda-fsh/pyobd/assets/70757160/232af47f-53fe-4ebf-994b-c4d4c699cf1e)

But when I try with PyOBD using the same settings, it won't connect : 
![image](https://github.com/barracuda-fsh/pyobd/assets/70757160/2d18353d-b245-4c66-b7b1-e080269c4a76)

Do you have an idea of what I'm doing wrong ?

Thank you !

**Comment by barracuda-fsh** [comment]
Maybe increase timeout and set auto baud rate?

**Comment by barracuda-fsh** [comment]
And maybe flip the switch if it has one.

**Comment by louisonsarlinmagnus** [comment]
I set everything to auto and flipping the switch and still can't connect. Is there any way to get some logs ?

**Comment by barracuda-fsh** [comment]
Run it from terminal or command prompt and you should get output. You can paste it here.

**Comment by louisonsarlinmagnus** [comment]
Nice !!
I run it with sudo in a terminal and worked like a charm !!! 
Thanks a lot !!

Do you think it could be possible to give more information on the GUI when connection failed ?
