### ISSUE TITLE
Detected: Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by thedapperissue** [barracuda-fsh/pyobd#16]
![Screenshot 2024-02-20 182056](https://github.com/barracuda-fsh/pyobd/assets/112028339/3295cdde-2371-44b1-8b4e-1a968528f7f2)

**Comment by barracuda-fsh** [comment]
Yes, it's a false positive. It's made solely from the code you see here.

**Comment by barracuda-fsh** [comment]
I rebuilt the executables in console mode now. Tell me if it still happens. I think it's OK now.

**Comment by pxFIN** [comment]
For me at least F-secure deepguard/heuristics detection blocks the .exe.. as well as Windows Defender..  

Reason: Suspicious:W32/Malware.a!fsmind

**Comment by barracuda-fsh** [comment]
Maybe someone can find a solution instead of pointing to what we already know?

**Comment by pxFIN** [comment]
> Maybe someone can find a solution instead of pointing to what we already know?

Sorry barracuda i was trying to answer your question about 'tell me if it still happens' not trying to be negative

I remember years back i was using pyinstaller and yes this same challenge was a problem.. I cant think of a easy solution for it

I think its quite well explained on this post

https://discuss.python.org/t/pyinstaller-false-positive/43171/11

**Comment by barracuda-fsh** [comment]
Ok, this sounds different. Thank you, I'll read that post.

**Comment by barracuda-fsh** [comment]
I looked into it and rebuilt the Windows executable. I think now it's reported it's good. Please correct me if I'm wrong. Please do, because I want to know for sure. Thanks to everyone for letting me know.

**Comment by pxFIN** [comment]
> I looked into it and rebuilt the Windows executable. I think now it's reported it's good. Please correct me if I'm wrong. Please do, because I want to know for sure. Thanks to everyone for letting me know.

Downloaded zip file, extracted files.. windows complains once but when you 'run anyway' app starts ok.. when you start app again no warnings from windows..  zero warnings from f-secure internet security
