### ISSUE TITLE
Error in byte to DTC conversion

### ISSUE THREAD

**Issue by yazyr** [barracuda-fsh/pyobd#18]
There seems to be some logic error in converting byte values to dtc. The logic is present in the 'decoders.py' script under the obd folder. I don't know what is the logic in converting byte values to dtc codes. If anyone has any idea, could you please guide me? It would be a huge favor.
The reason I'm saying this is because when I rise a specific error in OBDSim, a different error is showed on PyOBD. For example, an error of P0103 is shown as P0300 in PyOBD.
It is worth noting that this error is not present on other scanning software though, such as Torque or Car Scanner

**Comment by barracuda-fsh** [comment]
Is it possible that this is an error in the obdsim? I don't know. Oh you tried other software. Well this is the first time I am told about this. On my part it was accurate. It must be an error in python-obd library then. I'm not sure though.

**Comment by barracuda-fsh** [comment]
If someone finds a solution I will be greatful to you both.

**Comment by yazyr** [comment]
Same error was observed in Skoda Octavia Mk-II. Unplugging the MAP sensor coupler provided me an irrelevant error code. Also the code snippet that carries out the byte to dtc conversion has some comments that explain how the conversion is being done, which actually doesn't make sense. The binary equivalent of hexadecimal examples they have picked looks wrong. Or I am not sure I am interpreting the comments of the author properly. I have attached the code snippet performing the conversion below:

def parse_dtc(_bytes):
    """ converts 2 bytes into a DTC code """

    # check validity (also ignores padding that the ELM returns)
    if (len(_bytes) != 2) or (_bytes == (0, 0)):
        return None

    # BYTES: (16,      35      )
    # HEX:    4   1    2   3
    # BIN:    01000001 00100011
    #         [][][  in hex   ]
    #         | / /
    # DTC:    C0123

    dtc = ['P', 'C', 'B', 'U'][_bytes[0] >> 6]  # the last 2 bits of the first byte
    dtc += str((_bytes[0] >> 4) & 0b0011)  # the next pair of 2 bits. Mask off the bits we read above
    dtc += bytes_to_hex(_bytes)[1:4]

    # pull a description if we have one
    return (dtc, DTC.get(dtc, ""))
    
The above code snippet could be found in the decoders.py file inside the 'obd' folder

**Comment by barracuda-fsh** [comment]
In the old pyobd it was like this? Maybe it worked then. Can you try maybe?

def hex_to_int(str):
    i = eval("0x" + str, {}, {})
    return i

def decrypt_dtc_code(code):
   
    dtc = []
    current = code
    for i in range(0,3):
        if len(current)<4:
            raise "Tried to decode bad DTC: %s" % code

        tc = obd_sensors.hex_to_int(current[0]) #typecode
        tc = tc >> 2
        if   tc == 0:
            type = "P"
        elif tc == 1:
            type = "C"
        elif tc == 2:
            type = "B"
        elif tc == 3:
            type = "U"
        else:
            raise tc

        dig1 = str(obd_sensors.hex_to_int(current[0]) & 3)
        dig2 = str(obd_sensors.hex_to_int(current[1]))
        dig3 = str(obd_sensors.hex_to_int(current[2]))
        dig4 = str(obd_sensors.hex_to_int(current[3]))
        dtc.append(type+dig1+dig2+dig3+dig4)
        current = current[4:]
    return dtc

**Comment by barracuda-fsh** [comment]
I fixed it hopefully now. I used the code from older pyobd for dtc parsing. Can you test if it works properly now? I don't know how to trigger a dtc code in simulator. Download the latest source code to test.

**Comment by barracuda-fsh** [comment]
Please do it as soon as possible. You said it would be a huge favor to fix is, so let's do it.

**Comment by barracuda-fsh** [comment]
I can test it myself now with obdsim. It's not working properly yet, but I will fix it.

**Comment by barracuda-fsh** [comment]
I can confirm that def parse_dtc(_bytes): function is working properly. The bug is somewhere else.

**Comment by barracuda-fsh** [comment]
https://github.com/brendan-w/python-OBD/issues/61

I changed decoders.py

d += message.data[2:]

to this

d += message.data[1:3]

Now it shows the DTC correctly but it only works for 1 DTC. Help with this would be appreciated.

**Comment by barracuda-fsh** [comment]
I added another fix, so now it displays up to 2 DTC's correctly. If there are more than 2 DTC's stored in the ECU it will not display all of them.

**Comment by barracuda-fsh** [comment]
I found a solution, it was not trivial. I implemented it into latest code and you can see it under changes. Now it works properly for 1 up to how many you want DTC's. Maybe this should still be under observation under different cars and if someone can compare to other programs if it works well? I tested under obdsim obd simulator.
