### ISSUE TITLE
Where to find the standalone executables ?

### ISSUE THREAD

**Issue by Chralu** [barracuda-fsh/pyobd#2]
Hello,

thanks for that promising project !

The Readme indicates there are standalone executables to download, but I can't find them :/
Could you give more indications on where to find them ?

In the meantime, I'll try running the script

Thank you :)

**Comment by patgd** [comment]
Read through the rest of the README.md. There is a section on [Creating the Executable](https://github.com/barracuda-fsh/pyobd#creating-the-executable).

**Comment by barracuda-fsh** [comment]
I used to have tthem under downloads, but I will have to make new ones. The Linux version is there, I have to make Mac and Windows version. Coming ASAP.

**Comment by nevi-me** [comment]
> I used to have tthem under downloads, but I will have to make new ones. The Linux version is there, I have to make Mac and Windows version. Coming ASAP.

Thank you, also only saw the Linux one

**Comment by barracuda-fsh** [comment]
Now there's a new version 1.15 and all the executables with it. I would be glad if you try it out.
