### ISSUE TITLE
check if connecting to the car works with practically any ELM327 adapter

### ISSUE THREAD

**Issue by barracuda-fsh** [barracuda-fsh/pyobd#2]
I need to check if connecting to the car works with practically any ELM327 adapter and possibly fix it if some don't work. If someone has issues, feel free to comment and I will try to fix them also.

**It probably works on all USB ELM327 adapters(especially original ones, not copies).**

So far these have been confirmed to work:
-OBDPro USB Scantool (http://www.obdpros.com/product_info.php?products_id=133)
-OBDLink SX (https://www.obdlink.com/products/obdlink-sx/)
-Chinese USB ELM OBD2 (1.5a)
...

**Comment by jcw73** [comment]
First of all, thanks for updating this.

I am using pyobd on FreeBSD with an OBDLink SX adapter which claims ELM327 compatibility. I am able to connect to the OBDLink adapter at my desk using 'cu -l /dev/cuaU0 -s 115200' and issue some trivial AT commands like ATI and ATL 1.

When I attempt to connect to my 2001 Miata, I get the following:

[obd.elm327] Failed to read port
[obd.elm327] ATE0 did not return 'OK'
[obd.obd] Cannot load commands: No connection to car

I realize this is a pretty sparse report. If you have some troubleshooting tips, I'd be glad to hear them and report back.

I'll add that the COMPORT setting used to provide an option to enter a value in the configuration UI.  That is gone now and replace with "AUTO". I was able to edit .pyobdrc using COMPORT = /dev/cuaU0 which seemed to work at least as far as getting pyobd to communicate with my OBDLink adapter. /dev/ttyACM0 seems to be linux specific.

Regards,
Jason

**Comment by barracuda-fsh** [comment]
Hi! ATE0 is for echo off. It speeds up operations a bit. If you set all settings to AUTO or automatic, does it not work? Or if you manually type in ATE0 in the terminal, does it return OK? Maybe, some wait times need to be added. Did you try the latest release from here that I published? I'll be glad to help you make it work.

**Comment by barracuda-fsh** [comment]
The catch must be here: in folder /obd/elm327.py

        # -------------------------- ATE0 (echo OFF) --------------------------
        r = self.__send(b"ATE0", delay=2)
        if not self.__isok(r, expectEcho=True):
            self.__error("ATE0 did not return 'OK'")
            return

I changed delay=1 to delay=2 now. Try if it works. Also try setting expectEcho to False instead of True and tell me what works.

**Comment by jcw73** [comment]
I pulled your change and tried to connect to the miata again.

I think my problem was strictly baud rate related. I was able to connect at 115200 bps, but not 9600 bps. So, somewhat of a success with the OBLink SX.

I was able to view parameters on the "Tests" tab of the UI. I was not able to view any parameters on the "Sensors" tab.

While I was using pyobd I made some other observations.  Should I add a new issue for each of them or report them here?  BTW, I am brandy new to github so I am unaware of typical practices here.

**Comment by barracuda-fsh** [comment]
So it partially works now with the baud rate 115200? You must know that every ELM327 device is manually set to a specific baud rate. You can change it though, but manually in a terminal, with special commands.

Ok, so sensors do not work in your case. hmm Do you get any errors so I can relate to it?

Yes you can create issues for other observations, but it's probably best you do that when it's fully working. I guess you can, no problem. Well I think there are different practices when there are different people maintaining code. I am also a bit new to github, so don't worry.

I will also post new code very soon, it's more stable and has new functions(graphs). I just need to test it a little bit. Will publish it in 1-3 days.

**Comment by jcw73** [comment]
AUTO baud rate did not work for me. Nor did AUTO comport.

I didn't see any errors regarding the lack of sensors data.

My other observations were UI items. I'll post those separately.

I will wait for the new code for further testing.

**Comment by barracuda-fsh** [comment]
Try turning the engine on, leaving it on and then connecting.

**Comment by barracuda-fsh** [comment]
Also please try using these versions of the libraries(it was tested on them):
wxpython==4.1.1
pyserial==3.5

And if that doesn't work, maybe it's FreeBSD. It was never tested on FreeBSD. Can you try Linux? I am using Debian Linux, for example.

**Comment by jcw73** [comment]
I tried connecting after starting the engine. No difference on the Miata.

I tried hooking up to my '18 Tacoma.  Worked great.  Depressed the gas pedal. Saw the RPM sensor respond.

For posterity. I have wxpython version 4.0.7_2. I have pyserial version 3.5_1.

**Comment by barracuda-fsh** [comment]
Thank you very much for the feedback. I'm very glad it worked on another car. At least that.

Yes, I hope also for a wider audience. Thank you.

**Comment by barracuda-fsh** [comment]
I found out now, why your Miata doesn't work with this. Japanese cars have: Full OBD-II Compliance for 2008 and onward | Limited Compliance from 2003-07.

That's why it doesn't work.
