### ISSUE TITLE
AttributeError: 'MyApp' object has no attribute 'sensor_id'. Code bug?

### ISSUE THREAD

**Issue by Heavygrass** [barracuda-fsh/pyobd#29]
Hi Guys!

Thank you for this awesome project!
I just thought developers may be interested in the Linux terminal output below that might be a code issue?:

`Available ports: ['/dev/ttyUSB0']
Open port event.
Traceback (most recent call last):
  File "DELETED/GIT/pyobd/pyobd.py", line 2160, in OpenPort
    self.sensor_control_on()
  File "DELETED/GIT/pyobd/pyobd.py", line 1377, in sensor_control_on
    self.sensors.Bind(wx.EVT_LIST_ITEM_ACTIVATED, sensor_toggle, id=self.sensor_id)
                                                                    ^^^^^^^^^^^^^^
AttributeError: 'MyApp' object has no attribute 'sensor_id'. Did you mean: 'sensors'?
`

Please see the last line.
Ran as:
    python3 pyobd.py

I did "git clone" on Jul 10, 2024 from the main branch I believe, so it should be relevant.
I followed Linux installation instructions from the main GIT page.
Observed the same output above both when adapter connected to the car and when disconnected from the car.
It still connected to the car well.

Adapter: ELM327.

Ubuntu 24.04 Cinnamon (almost fresh install).
Kernel: 6.8.0-38-generic
Python 3.12.3 (main, Apr 10 2024, 05:33:47) [GCC 13.2.0] on linux

Thank you again for this awesome work!

**Comment by barracuda-fsh** [comment]
I think I fixed it now. Please try again with the latest code.
