### ISSUE TITLE
Changing One Setting in Configure Overwrites All Settings in .pyobdrc

### ISSUE THREAD

**Issue by jcw73** [barracuda-fsh/pyobd#3]
Regarding menu OBDII > Configure

If you change one setting in configure, all settings in .pyobdrc are overwritten.

This was problematic for me because neither AUTO in baud rate or in comport worked. The configure UI has no option to manually enter a comport. I manually edited .pyobrc to set comport=/dev/cuaU0.  Later I edited baudrate in the configure dialog and did not realize that the value of  comport was overwritten to the hardcoded value of AUTO.

If one does not ever use the configure dialog, then one avoids their configuration being overwritten.

**Comment by barracuda-fsh** [comment]
I will look into this, as soon as I can.

**Comment by barracuda-fsh** [comment]
I don't see this problem anywhere and I have tried it. You don't need to enter comport manually. If you're doing it right, you will get a comport displayed, besides auto. If you don't have a comport, then the only thing you will have is AUTO. Some devices are powered by the car, not the USB, so you will not have a comport displayed until you turn the car on and have it connected by the USB at the same time.
