### ISSUE TITLE
FIxes to Readme

### ISSUE THREAD

**Issue by Ericd789** [barracuda-fsh/pyobd#3]
This is a very interesting project, I look forward to getting my cable and trying this out on my car. In the mean time I cleaned up my readme so that it would be easier to read. I didn't mess with the text since i'm not sure what your plans for the readme is but any changes you'd like me to make i'd be more than happy to do.

**Comment by Ericd789** [comment]
#4

**Comment by barracuda-fsh** [comment]
Thank you, I made a merge.

**Comment by barracuda-fsh** [comment]
Made a merge.
