### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by j86schroeder** [barracuda-fsh/pyobd#35]
Can we add the ability to show 8 graphs instead of 4 graphs on the "Graphs" tab?

**Comment by barracuda-fsh** [comment]
Yes we can, but it involves quite a bit of work.

**Comment by barracuda-fsh** [comment]
I made it. I need to check it a bit before I upload.

**Comment by barracuda-fsh** [comment]
Done. 8 graphs are now under the latest code. Please test it and report back.

**Comment by barracuda-fsh** [comment]
I hope your cpu is fast enough to handle 8 graphs.

**Comment by greendoescode** [comment]
> I hope your cpu is fast enough to handle 8 graphs.

when you say fast enough, what are you running on?
My laptop might die if I try it lol

**Comment by barracuda-fsh** [comment]
i7-4790k is what I'm running on and it says it takes 75% of the core to run it. I don't know. Just try and you'll see. Maybe it will run ok.
