### ISSUE TITLE
Some UI Elements Seem to Have No Effect

### ISSUE THREAD

**Issue by jcw73** [barracuda-fsh/pyobd#4]
Regarding menu OBDII > Disconnect and menu File > Exit

Neither of these UI elements seems to have any effect. The only way to exit pybobd is to use CTRL-C in the terminal where I started pyobd.

**Comment by barracuda-fsh** [comment]
Yes, sometimes if something goes wrong, disconnect and exit don't work. I did already work on this, it's in the new code that I will post very very soon. I hope then it works every time. If not, then I have some more work to do, yes.
