### ISSUE TITLE
Please consider making pyobd PEP517 compliant by adding pyproject.toml, etc, and placing it on https://pypi.org ?

### ISSUE THREAD

**Issue by yurivict** [barracuda-fsh/pyobd#5]
This should install the executable "pyobd" into bin/.

This would make it easy to create ports/packages for it, and this would make it easier to install for users.

Thanks,
Yuri

**Comment by Kydlaw** [comment]
Maybe barracuda-fsh doesn't want to create a lib out of this code.

But that would be interesting to define at least the minimum version of Python required in this project.

**Comment by yurivict** [comment]
> Maybe barracuda-fsh doesn't want to create a lib out of this code.

It's not about making it into a lib.
PEP517 allows to install executables in a uniform way which makes it easy to install using standard methods.

**Comment by gray-adeyi** [comment]
The name pyobd and obd is already taken on pypi

**Comment by yurivict** [comment]
@gray-adeyi 

Just name it pyobd2 or obd2 then.
Many other projects solve this problem this way.

**Comment by gray-adeyi** [comment]
Okay great! I'll be working on it . Pyobd2 it is

**Comment by chrisdebian** [comment]
And rename for future OBD versions?

Cheers,

Chris
chris_debian

**Comment by Kydlaw** [comment]
I updated the PR to use pyobd2
